[default]
api_key = "AIzaSyBqokbE_E6kFtZNfbXctvRt14FzQ7ru9_w"

[listings]
"Kochi Villa" = { username = "0923133313", password = "0923133313" }
"Mee Villa" = { username = "meevilla", password = "meevilla" }
"Sense Villa" = { username = "sensevilla", password = "sensevilla" }
"Maya Villa" = { username = "0833136688", password = "0833136688" }
"Sense Pool Villa" = { username = "sensepoolvilla", password = "sensepoolvilla" }
"Sense Building" = { username = "sensebuilding", password = "sensebuilding" }
"ALC 1710" = { username = "nguyentienthanhtung", password = "nguyentienthanhtung" }
"ALC 2204" = { username = "nguyentienthanhtung", password = "nguyentienthanhtung" }
"ALC 1011" = { username = "nguyentienthanhtung", password = "nguyentienthanhtung" }
"ALC 708" = { username = "nguyentienthanhtung", password = "nguyentienthanhtung" }
"ALC 2010" = { username = "nguyentienthanhtung", password = "nguyentienthanhtung" }
